#!/bin/bash

if [ $# == 1 ]
then
    if [ $1 == '-' ]
    then
        TARGET=@{-1}
    else
        TARGET=$1
    fi
else
    TARGET=master
fi

git diff --numstatgit diff --numstat $TARGET HEAD | awk '{added+=$1}{deleted+=$2}{files+=1}{total+=$1+$2}END{print "LINES ADDED: " added " DELETED: " deleted " (TOTAL: " total ") IN " files " FILES"}'
 $TARGET HEAD | awk '{sum+=$1+$2}END{print sum}'
