#!/bin/bash

if [ $# == 1 ]
then
    if [ $1 == '-' ]
    then
        TARGET=@{-1}
    else
        TARGET=$1
    fi
else
    TARGET=master
fi

git diff --numstat $TARGET HEAD | awk '{sum+=$1+$2}END{print sum}'